- name: Generate Flask app configuration file
  template:
    src: flask.conf.j2
    dest: /etc/systemd/system/{{ flask_app_name }}.service
  notify: Restart Flask app

- name: Generate Flask app
  template:
    src: app.py.j2
    dest: /home/ubuntu/{{ flask_app_name }}/app.py
  notify: Restart Flask app
  
- name: Restart Flask app
  systemd:
    name: "{{ flask_app_name }}"
    state: restarted

- name: Define Flask app routes
  block:
    - name: Define home page route
      lineinfile:
        path: /home/ubuntu/{{ flask_app_name }}/app.py
        line: '    @app.route("/")\n    def hello():\n        return "{{ flask_app_message }}"'
  notify: Restart Flask app
